[package]
name = "encoderfile-py"
version = "0.4.3"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "encoderfile"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"

[dependencies.encoderfile]
path = "../encoderfile"
version = "0.4.3"
