repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: bash -c 'cargo fmt --all -- --check'
        language: system
        types: [rust]
      - id: cargo-check
        name: cargo check
        entry: bash -c 'cargo check --all-features'
        language: system
        types: [rust]
      - id: schema-drift-check
        name: schema drift check
        entry: bash -c 'cargo run --bin generate-encoderfile-config-schema && git diff --quiet -- schemas/encoderfile-config-schema.json'
        language: system
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9  # use the latest release tag
    hooks:
      - id: ruff
        name: ruff check
        args: [--fix]  # optional: auto-fix issues
      - id: ruff-format
        name: ruff format
