site_name: Encoderfile
site_url: https://mozilla-ai.github.io/encoderfile/
repo_url: https://github.com/mozilla-ai/encoderfile

theme:
  logo: assets/favicon.svg
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.svg
  name: material
  language: en
  palette:
    scheme: slate
    primary: grey
    accent: deep orange
  features:
    - navigation.instant
    - navigation.tabs

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Building Encoderfiles:
    - Building with Docker: building_encoderfiles/docker.md
  - Cookbooks:
      - Token Classification (NER): cookbooks/token-classification-ner.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - Contributing: CONTRIBUTING.md
  - Transforms:
      - Transforms: transforms/index.md
      - Reference: transforms/reference.md
  - Reference:
    - CLI Reference: reference/cli.md
    - API Reference: reference/api-reference.md
    - Building Guide: reference/building.md

plugins:
  - include-markdown

markdown_extensions:
  - footnotes
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
