site_name: Encoderfile
site_url: https://mozilla-ai.github.io/encoderfile/
repo_url: https://github.com/mozilla-ai/encoderfile

theme:
  logo: assets/favicon.svg
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.svg
  name: material
  language: en
  palette:
    scheme: slate
    primary: grey
    accent: deep orange
  features:
    - navigation.instant
    - navigation.tabs
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started:
    - Building from Source â€” CLI: getting_started/build_from_source_cli.md
  - Transforms:
      - Transforms: transforms/index.md
      - Reference: transforms/reference.md
  - Reference:
    - Encoderfile Build CLI: reference/encoderfile_util_cli.md
    - Encoderfile Binary CLI: reference/encoderfile_binary_cli.md

plugins:
  - include-markdown

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
