site_name: Encoderfile
site_url: https://mozilla-ai.github.io/encoderfile/
repo_url: https://github.com/mozilla-ai/encoderfile

theme:
  logo: assets/favicon.svg
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.svg
  name: material
  language: en
  palette:
    scheme: slate
    primary: grey
    accent: deep orange
  features:
    - navigation.instant
    - navigation.tabs

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - CLI : cli.md
  - API Reference: reference/api-reference.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - Contributing: CONTRIBUTING.md
  - Transforms:
      - Transforms: transforms/index.md
      - Reference: transforms/reference.md
  - Reference:
    - Building Guide: reference/building.md
    - CLI Reference: reference/cli-reference.md

plugins:
  - include-markdown

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
