[project]
name = "encoderfile"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.0",
    "onnxruntime>=1.23.1",
    "optimum[onnxruntime]>=2.0.0",
    "pip>=25.2",
    "protobuf>=6.33.0",
    "torch>=2.8.0",
    "transformers>=4.55.0",
]
