encoderfile:
  name: my-model-2
  path: models/token_classification
  model_type: token_classification
  output_dir: ./my-model-2.encoderfile
  transform:
    path: transforms/token_classification/softmax_logits.lua
