[[bin]]
name = "encoderfile"
path = "src/main.rs"

[package]
name = "encoderfile"
version = "0.3.0"
edition = "2024"
license = "Apache-2.0"
readme = "../README.md"
description = "Distribute and run transformer encoders with a single file."

[dependencies]
clap_derive = "4.5.49"
directories = "6.0.0"
lazy_static = "1.5.0"
sha2 = "0.10.9"
tera = "1.20.1"

[features]
dev-utils = []

[dev-dependencies]
tempfile = "3.23.0"

[dependencies.tokenizers]
workspace = true

[dependencies.anyhow]
workspace = true

[dependencies.clap]
workspace = true

[dependencies.rand]
workspace = true

[dependencies.schemars]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.ndarray]
workspace = true

[dependencies.encoderfile-core]
path = "../encoderfile-core"
version = "0.3.0"
features = [ "transforms",]
default-features = false

[dependencies.figment]
version = "0.10.19"
features = [ "env", "serde_yaml", "yaml",]

[dependencies.serde]
workspace = true

[dependencies.ort]
workspace = true

[dev-dependencies.uuid]
version = "1.18.1"
features = [ "v4",]
