[package]
name = "encoderfile-test"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.52"
anyhow = "1.0.100"
tokio = { version = "1.48.0", features = ["full"] }

[dependencies.encoderfile-core]
path = "../encoderfile-core"

[features]
bench = []
